SAM_V7/Controllers/ApproversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAM_V7.Models;

namespace SAM_V7.Controllers
{
    public class ApproversController : Controller
    {
        private SAM_V7Context db = new SAM_V7Context();

        // GET: Approvers
        public ActionResult Index()
        {
            return View(db.Approvers.ToList());
        }

        // GET: Approvers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Approvers approvers = db.Approvers.Find(id);
            if (approvers == null)
            {
                return HttpNotFound();
            }
            return View(approvers);
        }

        

        // GET: Approvers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Approvers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PSUPassport,TitleName,Name,LastName,OrganName,Position,Email,Tel")] Approvers approvers)
        {
            if (ModelState.IsValid)
            {
                db.Approvers.Add(approvers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(approvers);
        }

        // GET: Approvers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Approvers approvers = db.Approvers.Find(id);
            if (approvers == null)
            {
                return HttpNotFound();
            }
            return View(approvers);
        }

        // POST: Approvers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PSUPassport,TitleName,Name,LastName,OrganName,Position,Email,Tel")] Approvers approvers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(approvers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(approvers);
        }

        // GET: Approvers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Approvers approvers = db.Approvers.Find(id);
            if (approvers == null)
            {
                return HttpNotFound();
            }
            return View(approvers);
        }

        // POST: Approvers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Approvers approvers = db.Approvers.Find(id);
            db.Approvers.Remove(approvers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAM_V7/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAM_V7.Models;

namespace SAM_V7.Controllers
{
    public class OrganizationsController : Controller
    {
        private SAM_V7Context db = new SAM_V7Context();

        // GET: Organizations
        public ActionResult Index()
        {
            return View(db.Organizations.ToList());
        }

        // GET: Organizations/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organizations organizations = db.Organizations.Find(id);
            if (organizations == null)
            {
                return HttpNotFound();
            }
            return View(organizations);
        }

        // GET: Organizations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrganNo,OrganName,PSUPassport,TitleAdviserName,AdviserName,AdviserLastName,AdviserEmail,AdviserTel,StartPositionDate,EndPositionDate")] Organizations organizations)
        {
            if (ModelState.IsValid)
            {
                db.Organizations.Add(organizations);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organizations);
        }

        // GET: Organizations/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organizations organizations = db.Organizations.Find(id);
            if (organizations == null)
            {
                return HttpNotFound();
            }
            return View(organizations);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrganNo,OrganName,PSUPassport,TitleAdviserName,AdviserName,AdviserLastName,AdviserEmail,AdviserTel,StartPositionDate,EndPositionDate")] Organizations organizations)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organizations).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organizations);
        }

        // GET: Organizations/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organizations organizations = db.Organizations.Find(id);
            if (organizations == null)
            {
                return HttpNotFound();
            }
            return View(organizations);
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Organizations organizations = db.Organizations.Find(id);
            db.Organizations.Remove(organizations);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAM_V7/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAM_V7.Models;

namespace SAM_V7.Controllers
{
    public class StaffsController : Controller
    {
        private SAM_V7Context db = new SAM_V7Context();

        // GET: Staffs
        public ActionResult Index()
        {
            return View(db.Staffs.ToList());
        }

        // GET: Staffs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PSUPassport,StaffTitleName,StaffName,StaffLastName,OrganName,Position,StaffEmail,StaffTel")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PSUPassport,StaffTitleName,StaffName,StaffLastName,OrganName,Position,StaffEmail,StaffTel")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAM_V7/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAM_V7.Models;

namespace SAM_V7.Controllers
{
    public class UsersController : Controller
    {
        private SAM_V7Context db = new SAM_V7Context();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PSUPassport,TitleName,Name,LastName,Faculty,Major,OrganName,Position,Email,Tel,StartPositionDate,EndPositionDate")] Users users)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(users);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(users);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PSUPassport,TitleName,Name,LastName,Faculty,Major,OrganName,Position,Email,Tel,StartPositionDate,EndPositionDate")] Users users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Users users = db.Users.Find(id);
            db.Users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAM_V7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
  
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
  
    @if (Session["PSUPassport"] != null)
    {
        <header>
        <img src="~/image/Header2.png" alt="Mountain View" style="width:100%;height:100%;">
            </header>
    }


    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @if (Session["PSUPassport"] != null && Session["PSUPassport"].ToString() == "admin")
                {
                    @Html.ActionLink("SAM", "Index", "Staffs", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (Session["PSUPassport"] != null && Session["Position"].Equals("Student Activity Staffs"))
                {
                    @Html.ActionLink("SAM", "Index", "Proposals", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if ((Session["PSUPassport"] != null) && (Session["Position"].Equals("Advisor") || Session["Position"].Equals("Student Council") ||
              Session["Position"].Equals("Head of Student Activity section") || Session["Position"].Equals("Head of Student Affairs division") || Session["Position"].Equals("Assistant to the President for Student Development") ||
              Session["Position"].Equals("Vice President for Academic Affairs for Phuket Campus")))
                {
                    @Html.ActionLink("SAM", "Index", "Proposals", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (Session["PSUPassport"] != null && Session["OrganName"].Equals("Student Union"))
                {
                    @Html.ActionLink("SAM", "Index", "Proposals", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (Session["PSUPassport"] == null)
                {
                    @Html.ActionLink("SAM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("SAM", "Index", "Proposals", new { area = "" }, new { @class = "navbar-brand" })
                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["PSUPassport"] != null && Session["PSUPassport"].ToString() == "admin")
                    {
                        <li> @Html.ActionLink("Staff Management", "Index", "Staffs") </li>
                    }

                    else if (Session["PSUPassport"] != null && Session["Position"].Equals("Student Activity Staffs"))
                    {

                        <li> @Html.ActionLink("Proposal Management", "Index", "Proposals") </li>
                        <li> @Html.ActionLink("Oganization Management", "Index", "Organizations") </li>
                        <li> @Html.ActionLink("User Management", "Index", "Users") </li>
                        <li> @Html.ActionLink("Approver Management", "Index", "Approvers") </li>
                    }

                    else if ((Session["PSUPassport"] != null) && (Session["Position"].Equals("Advisor") || Session["OrganName"].Equals("Student Council") ||
                Session["Position"].Equals("Head of Student Activity section") || Session["Position"].Equals("Head of Student Affairs division") || Session["Position"].Equals("Assistant to the President for Student Development") ||
                Session["Position"].Equals("Vice President for Academic Affairs for Phuket Campus")))
                    {

                        <li> @Html.ActionLink("Proposal Management", "Index", "Proposals") </li>
                    }

                    else if (Session["PSUPassport"] != null && Session["OrganName"].Equals("Student Union"))
                    {

                        <li> @Html.ActionLink("Proposal Management", "Index", "Proposals") </li>
                    }
                    else if (Session["PSUPassport"] == null)
                    {

                    }
                    else
                    {
                        <li> @Html.ActionLink("Proposal Management", "Index", "Proposals") </li>
                    }

                </ul>

                @if (Session["PSUPassport"] != null)
                {
                    <ul class="nav navbar-nav navbar-right " align="right">
                        <li style="margin-top:15px"><span class="label label-default">@Html.DisplayName("Welcome, " + @Session["Name"].ToString()+" ["+ @Session["Position"].ToString()+"]") </span></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    </ul>
                }

                else
                {
                    <ul class="nav navbar-nav navbar-right " align="right">
                        <li>@Html.ActionLink("Login", "Index", "Home")</li>
                    </ul>
                }


            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>